### ISSUE TITLE
User::name, User::username and User::email confusion

### ISSUE THREAD

**Issue by alimturkmen** [bounswe/bounswe2018group10#130]
### I'm submitting a ...

- [ ] bug report
- [ ] feature request
- [x] support request

In `User` model, there are two fields named name and username. If a user were to sign up to the website, we should ask for his email and username, both of which must be _unique_ and _required_, then when creating his profile we should ask for the name. Therefore name should be moved from User to Profile class, IMHO.

```python

class User(AbstractBaseUser, PermissionsMixin):
    # ...
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=50, unique=True, null=True, blank=True)
```

**Comment by barisesmer** [comment]
We ask users to submit several information such as their **actual name**, email and a username for their account. Name in the user model corresponds to actual name of the user. In my opinion these three fields should be unique for one **user account**, therefore they are in the user model and not in the profile models. Since this is a design issue, we can change this as we like but this is the intended usage right now.

**Comment by barisesmer** [comment]
I am closing this issue since we agreed on the design.
