### ISSUE TITLE
Profile Pictures

### ISSUE THREAD

**Issue by sbasrik** [bounswe/bounswe2018group10#40]
### I'm submitting a ...

- [ ] bug report
- [ ] feature request
- [x] support request

### Expected behavior
All team members are expected to have profile pictures so everyone can know who is who.

### Actual behavior
Some team members hide their faces.

**Comment by afcelimli** [comment]
Did you realize you also assign Cihat:)

**Comment by kaanozgen12** [comment]
Really?  :))))))))

On Mar 11, 2018 1:13 PM, "afcelimli" <notifications@github.com> wrote:

Did you realize you also assign Cihat:)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/bounswe/bounswe2018group10/issues/40#issuecomment-372103912>,
or mute the thread

**Comment by alimturkmen** [comment]
An interesting request but done :)

**Comment by eutkan** [comment]
Done

**Comment by meverg** [comment]
done and I agree on Cihat's assignment

**Comment by kaanozgen12** [comment]
Done

**Comment by afcelimli** [comment]
Done

**Comment by kilicbaran** [comment]
Done
