### ISSUE TITLE
Backstabbers not working for popular users 

### ISSUE THREAD

**Issue by alimturkmen** [bounswe/bounswe2018group10#69]
Users that have more than 270 followers or friends will get stuck in the home page due to rate limits of twitter API. Don't know how to fix it, anyone can fix this bug?
### I'm submitting a ...

- [x] bug report

**Comment by abdusco** [comment]
270 is a very specific number. It sounds like an API limit to me. Maybe check how many fetches Twitter allows in a time frame?

**Comment by kilicbaran** [comment]
1. You may specify the count parameter in the API. The default is 20. Also the documentation says it allows 15 requests for 15-min window. 15*20=300 ~270 This may be the limitation. [Twitter get friend list API](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-list)

2. You may use sleep in your function to avoid rate limit. [Here is an example from Stackoverflow](https://stackoverflow.com/questions/17431807/get-all-follower-ids-in-twitter-by-tweepy) But this is probably undesirable because it will keep the user waiting for a long period.

**Comment by alimturkmen** [comment]
Thanks for your help guys :)
